### ISSUE TITLE
Add indexes section to configuration for auto creation of index pages

### ISSUE THREAD

**Issue by yaph** [yaph/logya#109]
Auto create index pages, that don't appear in document index, i.e. need not be excluded in `get_docs` calls in templates.

Sample config in `site.yaml`:

```
indexes:
  - url: /posts/
    docs: /post/
    template: index.html
  - url: /blog/
    docs: /blog/
    template: index.html
```
